version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  books:
    build:
      context: ./books
    container_name: books
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    ports:
      - "5001:5000"
    restart: always

volumes:
  mongo-data:
