name: assignment3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Capture start time and submitters
        run: |
          echo $(date -Iminutes) > log.txt
          echo "Yair Nadler" >> log.txt

      - name: Build and load the books service image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: ./books
          tags: books-service:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Log build status
        run: |
          if [ "${{ steps.build_image.outcome }}" == "success" ]; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
          fi

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: books-service
          path: /tmp/image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: books-service
          path: /tmp

      - name: Download log file
        uses: actions/download-artifact@v4
        with:
          name: log

      - name: Load Docker image
        run: docker load -i /tmp/image.tar

      - name: Clean up any existing MongoDB containers
        run: |
          docker ps -q --filter "ancestor=mongo" | xargs -r docker stop
          docker ps -a -q --filter "ancestor=mongo" | xargs -r docker rm

      - name: Wait for MongoDB to be ready
        run: sleep 30

      - name: Run docker-compose up
        run: |
          docker compose up --build -d
          if [ $? -eq 0 ]; then
            echo "Container up and running" >> log.txt
          else
            echo "Container failed to run" >> log.txt
            exit 1
          fi

      - name: Set up python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          cd tests
          pytest -v assn3_tests.py > assn3_test_results.txt

      - name: Log test results
        run: |
          if grep -q "tests failed" ../assn3_test_results.txt; then
            echo "tests failed" >> log.txt
          else
            echo "tests succeeded" >> log.txt
          fi

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
          overwrite: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GH_test_results
          path: tests/assn3_test_results.txt

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: books-service
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/image.tar

      - name: Clean up any existing MongoDB containers
        run: |
          docker ps -q --filter "ancestor=mongo" | xargs -r docker stop
          docker ps -a -q --filter "ancestor=mongo" | xargs -r docker rm

      - name: Wait for MongoDB to be ready
        run: sleep 30

      - name: Run docker-compose up
        run: docker compose up --build -d

      - name: Wait for books service to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5001/books; then
              echo "Books service is ready"
              break
            fi
            echo "Waiting for books service to be ready..."
            sleep 5
          done

      - name: Create books with POST requests
        run: |
          post_book() {
            for i in {1..5}; do
              response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d "$2" http://localhost:5001/books)
              if [ "$response" -eq 201 ]; then
                echo "Successfully posted book: $1"
                return 0
              else
                echo "Failed to post book: $1. Retrying in 5 seconds..."
                sleep 5
              fi
            done
            echo "Failed to post book: $1 after 5 attempts."
            exit 1
          }

          post_book "Adventures of Huckleberry Finn" '{"title":"Adventures of Huckleberry Finn", "ISBN":"9780520343641", "genre":"Fiction"}'
          post_book "The Best of Isaac Asimov" '{"title":"The Best of Isaac Asimov", "ISBN":"9780385050784", "genre":"Science Fiction"}'
          post_book "Fear No Evil" '{"title":"Fear No Evil", "ISBN":"9780394558783", "genre":"Biography"}'
          post_book "The Adventures of Tom Sawyer" '{"title":"The Adventures of Tom Sawyer", "ISBN":"9780195810400", "genre":"Fiction"}'
          post_book "I, Robot" '{"title":"I, Robot", "ISBN":"9780553294385", "genre":"Science Fiction"}'
          post_book "Second Foundation" '{"title":"Second Foundation", "ISBN":"9780553293364", "genre":"Science Fiction"}'

      - name: Execute specific requests and record the results
        run: |
          cd tests
          echo "Running queries from query.txt"
          touch response.txt
          while IFS= read -r line; do
            query_string="${line}"
            response=$(curl -s "http://localhost:5001/books${query_string}")
            status_code=$(curl -o /dev/null -s -w "%{http_code}\n" "http://localhost:5001/books${query_string}")
            if [ "$status_code" -eq 200 ]; then
              echo "query: ${query_string}" >> ../response.txt
              echo "response: ${response}" >> ../response.txt
            else
              echo "query: ${query_string}" >> ../response.txt
              echo "response: error ${status_code}" >> ../response.txt
            fi
          done < ../query.txt

      - name: Upload response file
        uses: actions/upload-artifact@v4
        with:
          name: response
          path: response.txt
